steps:
  # Build the Django application Docker image
  - name: 'gcr.io/cloud-builders/docker' 
    args:
      - 'build'
      - '-t'  # Tag the image
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/app-genai/genai-apps:latest'  # Use a consistent image name and consider a specific version tag
      - '.'   # Build context (the current directory)

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/app-genai/django-genai-apps:latest']  # Use the same image name as in the build step

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/app-genai/django-genai-apps:latest'  # List the final image to be stored

options:
  logging: CLOUD_LOGGING_ONLY  # or NONE to disable logging
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

